### ISSUE TITLE
[Question] Is there a way to hook into animation lifecycle events?

### ISSUE THREAD

**Issue by oliverswitzer** [benvp/live_motion#2]
Hi,

First off, I love this effort to make animations easier in LiveView.

I wanted to ask if a feature to hook into animation lifecycle events is something that would be in scope of this library? I'm thinking an API that would look like the following:

```.leex
  <LiveMotion.motion id="popcorn" on_animation_end="popcorn_animation_end" animate={[rotate: 360]}>
    <span>🍿</span>
  </LiveMotion.motion>
```

Then in your LiveView you can define an event handler for "popcorn_animation_end":

```
def handle_event("popcorn_animation_end", _params, socket) do 
  # LiveView code that removes the popcorn element
end
```

One challenge with this is probably going to be making it flexible to use from within live components, where you would need to specify `phx-target={@myself}` in the eex to get `handle_event` messages passed to your component.

Would be happy to try to contribute this change if you could point me in the right direction

**Comment by benvp** [comment]
I'm interested where this would be required. Can you describe a scenario? Technically it should be possible as there are lifecycle events for the animation in JS land. So we could push an event back to the server when the animation has finished. 

Regarding `phx-target={@myself}` I think we should require the user to add this when using it within a LiveComponent. `LiveMotion.motion` forwards all props which are not used by it directly.

*EDIT*: I missed the comment in your handle_event callback. So I guess you want to remove the element after the animation finished.  In general, I think these kind of things could be done directly on the client as they should not require a server round trip. 

If it's just the "removal" you can do something similar right now (without specifically removing the element from the DOM).

```
<LiveMotion.motion
  id="rectangle"
  class="w-24 h-24 bg-benvp-green rounded-lg"
  animate={[opacity: 0, display: "none"]}
  transition={[duration: 2]}
>
</LiveMotion.motion>
```

This should animate to `opacity: 0` first and afterwards hide the element.

**Comment by oliverswitzer** [comment]
Sorry, should’ve used a better example. We have a modal in our app that we were animating to fade out when closed. The modal contained a form that needed to be cleared after the modal is closed (creating a new changeset and clearing the old one)

Unfortunately due to the animation and not wanting to clear the form before the animation ended, this could only be achieved with a Process.send_after of the exact number of ms configured in the animation css, and storing an additional variable on the socket assigns.

My preference would have been to not hardcode the animating timing in both css and elixir, and I think the API of live motion would be perfect to accomplish this. 

To your second point about requiring to pass phx-target, that makes perfect sense.

Out of curiosity have you tried using this library with Surface yet? Id want to make sure that the `event` prop type for surface would also still work. I *think* it would work given that all props are passed through

**Comment by benvp** [comment]
Ah okay, makes sense. Wouldn't it be possible to have the form state be cleared upon opening the modal? 

I was also thinking about using `phx-remove={LiveView.JS.push("reset_form")}` but sadly this won't work as `phx-remove` is only triggered when the element is removed via DOM patching initiated from the server.

So for now I can't think of another way beside adding something like `on_finished` which accepts either a `Phoenix.LiveView.JS` or a string to initiate a server event. We would need to make sure that this is always triggered whenever _any_ animation finishes, as animations could be triggered via `LiveMotion.JS`, too.

Probably we would need to distinguish between normal animations and exit animations and have two props: `on_finished` and `on_exit`.

What do you think?
 
Also, I didn't tried using it with surface yet as I never used surface.

**Comment by oliverswitzer** [comment]
Hah! Good point. I wasn’t on that ticket so I’m not 100% why it wasn’t decided to clear the form on modal open instead of close.

In any case I do still feel it could be a useful thing to have access to. This is a bit of a stretch scenario, but imagine if that form was backed by PubSub and needed to be cleared for everyone on modal close, at which point we couldn’t rely on user input to clear it when opened.

I was hoping not to take away from the this libraries great promise of all animations happening on the client if possible. Should we try to avoid sending push events if the user hasn’t passed the prop that indicates that they want to hook into the animation lifecycle?

It may be a little tricky to handle LiveMotion.JS uses since it would be unclear to me what selector to pass to `pushEventTo` from the hook to indicate which component should receive the event. I guess you could pass phx-target in the LiveMotion.JS call?

Also, in terms of naming how does `on_animation_start` and `on_animation_end` sound? Just borrowing that naming convention from [Framer motion](https://www.framer.com/docs/component/#%23%23onanimationstart). Then perhaps `on_animation_exit`… though is there a reason users wouldn’t be able achieve what they need to through only the on_animation_end call?

Sorry, lots of thoughts. Would be happy to pair on this as well!

**Comment by benvp** [comment]
I think it wouldn't take away that the animations happen on the client - that's what's always happening. We are not sending any animation frames over the wire. 

Not sending any events when the user did not provide them shouldn't be too complicated and that's the way I'd like it to be implemented. 

I could imagine something like this for the implementation:

### `on_animation_start` and `on_animation_complete` (borrowed from Framer motion)

These props support either a `JS` command (e.g. `Phoenix.LiveView.JS.push/1`) or a simple string value. If the value is a string value, we translate this into a call to `Phoenix.LiveView.JS.push/1`.

The JS command will be added to the `data-motion` attribute (that's where the animation config lives in). This way we can grab the config when an animation is triggered and utilise `liveSocket.execJS` if any of the lifecycle hooks are present. 

This way we don't have to rely on `pushEvent` from the hook, because inside the event listeners (live_motion:animate, live_motion:hide, etc.) we are outside the hook scope. 

Also we would need to make that the `data-motion` attribute might be undefined if the target of the LiveMotion.JS call is not a `LiveMotion.motion` component but any HTML element.

Regarding `on_animation_exit` I thought that we would need a way to differentiate between the animations. For example if you only want to push an event when the element triggered an exit. Looking at Framer Motion here, we could pass the animation definition as params when calling `on_animation_complete` so there is a way to identify the triggered animation.

I'll start to implement this in the next couple of days as it seems useful to me, too. I will also convert the JS codebase to TypeScript as I am more confident developing in TypeScript when the JS codebase grows :)

**Comment by oliverswitzer** [comment]
@benvp sorry about the delay here, my company is making a big beta release push so I haven't had much time for outside-of-work stuff. 

I'm not sure I entirely follow along with all of the implementation details but I understand the gist of what you are suggesting I believe. I think the idea of passing either a string or a JS command makes a lot of sense and keeps the API flexible to server-side or client-side consumption of these lifecycle hooks. `on_animation_start` and `on_animation_complete` seem like great names for the lifecycle events as well

**Comment by benvp** [comment]
@oliverswitzer I finally had some time to implement that. 👍

**Comment by oliverswitzer** [comment]
That’s awesome, thanks for implementing!
